// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/p2p.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_UNKNOWN               MessageType = 0
	MessageType_MSG_HANDSHAKE_REQUEST     MessageType = 1
	MessageType_MSG_HANDSHAKE_RESPONSE    MessageType = 2
	MessageType_MSG_GET_METADATA_REQUEST  MessageType = 3
	MessageType_MSG_GET_METADATA_RESPONSE MessageType = 4
	MessageType_MSG_GET_CHUNK_REQUEST     MessageType = 5
	MessageType_MSG_GET_CHUNK_RESPONSE    MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MSG_UNKNOWN",
		1: "MSG_HANDSHAKE_REQUEST",
		2: "MSG_HANDSHAKE_RESPONSE",
		3: "MSG_GET_METADATA_REQUEST",
		4: "MSG_GET_METADATA_RESPONSE",
		5: "MSG_GET_CHUNK_REQUEST",
		6: "MSG_GET_CHUNK_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MSG_UNKNOWN":               0,
		"MSG_HANDSHAKE_REQUEST":     1,
		"MSG_HANDSHAKE_RESPONSE":    2,
		"MSG_GET_METADATA_REQUEST":  3,
		"MSG_GET_METADATA_RESPONSE": 4,
		"MSG_GET_CHUNK_REQUEST":     5,
		"MSG_GET_CHUNK_RESPONSE":    6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_p2p_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_p2p_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                           // Unique ID generated by the requestor to pair with a response
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=p2p.MessageType" json:"type,omitempty"` // Type of message contained in the payload
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                 // The serialized inner message payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_UNKNOWN
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *HandshakeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // This can be the file manifest's CID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_proto_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetadataRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"` // The JSON string bytes representing FileMeta
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_proto_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetadataResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMetadataResponse) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *GetMetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // The file manifest's CID
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_proto_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *GetChunkRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_proto_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *GetChunkResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetChunkResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *GetChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_p2p_proto protoreflect.FileDescriptor

const file_proto_p2p_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/p2p.proto\x12\x03p2p\"Z\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04type\x18\x02 \x01(\x0e2\x10.p2p.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"E\n" +
	"\x10HandshakeRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\\\n" +
	"\x11HandshakeResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"-\n" +
	"\x12GetMetadataRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x83\x01\n" +
	"\x13GetMetadataResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"K\n" +
	"\x0fGetChunkRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\"\x90\x01\n" +
	"\x10GetChunkResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*\xc9\x01\n" +
	"\vMessageType\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15MSG_HANDSHAKE_REQUEST\x10\x01\x12\x1a\n" +
	"\x16MSG_HANDSHAKE_RESPONSE\x10\x02\x12\x1c\n" +
	"\x18MSG_GET_METADATA_REQUEST\x10\x03\x12\x1d\n" +
	"\x19MSG_GET_METADATA_RESPONSE\x10\x04\x12\x19\n" +
	"\x15MSG_GET_CHUNK_REQUEST\x10\x05\x12\x1a\n" +
	"\x16MSG_GET_CHUNK_RESPONSE\x10\x06B@Z>github.com/IEEECS-VIT/p2p-model-distribution/internal/protocolb\x06proto3"

var (
	file_proto_p2p_proto_rawDescOnce sync.Once
	file_proto_p2p_proto_rawDescData []byte
)

func file_proto_p2p_proto_rawDescGZIP() []byte {
	file_proto_p2p_proto_rawDescOnce.Do(func() {
		file_proto_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_p2p_proto_rawDesc), len(file_proto_p2p_proto_rawDesc)))
	})
	return file_proto_p2p_proto_rawDescData
}

var file_proto_p2p_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_p2p_proto_goTypes = []any{
	(MessageType)(0),            // 0: p2p.MessageType
	(*Envelope)(nil),            // 1: p2p.Envelope
	(*HandshakeRequest)(nil),    // 2: p2p.HandshakeRequest
	(*HandshakeResponse)(nil),   // 3: p2p.HandshakeResponse
	(*GetMetadataRequest)(nil),  // 4: p2p.GetMetadataRequest
	(*GetMetadataResponse)(nil), // 5: p2p.GetMetadataResponse
	(*GetChunkRequest)(nil),     // 6: p2p.GetChunkRequest
	(*GetChunkResponse)(nil),    // 7: p2p.GetChunkResponse
}
var file_proto_p2p_proto_depIdxs = []int32{
	0, // 0: p2p.Envelope.type:type_name -> p2p.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_p2p_proto_init() }
func file_proto_p2p_proto_init() {
	if File_proto_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_p2p_proto_rawDesc), len(file_proto_p2p_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_p2p_proto_goTypes,
		DependencyIndexes: file_proto_p2p_proto_depIdxs,
		EnumInfos:         file_proto_p2p_proto_enumTypes,
		MessageInfos:      file_proto_p2p_proto_msgTypes,
	}.Build()
	File_proto_p2p_proto = out.File
	file_proto_p2p_proto_goTypes = nil
	file_proto_p2p_proto_depIdxs = nil
}
